Traceback (most recent call last):
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Check the location of AOI (areas of interest (reference data))

aoi = gpd.read_file('../data/aoi_NL_5_classes.shp')
print (aoi.head())

fig,ax = plt.subplots(1,1, figsize=(10,10))
show(ndvi_2015, transform=ndvi_meta['transform'], ax=ax, cmap='gray', alpha=0.25)
aoi.plot(column='land_cover', legend=True, ax=ax, cmap='Set1')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_10468\1311599434.py[0m in [0;36m<cell line: 3>[1;34m()[0m
[0;32m      1[0m [1;31m# Check the location of AOI (areas of interest (reference data))[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [0maoi[0m [1;33m=[0m [0mgpd[0m[1;33m.[0m[0mread_file[0m[1;33m([0m[1;34m'../data/aoi_NL_5_classes.shp'[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [0mprint[0m [1;33m([0m[0maoi[0m[1;33m.[0m[0mhead[0m[1;33m([0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mNameError[0m: name 'gpd' is not defined
NameError: name 'gpd' is not defined

