Traceback (most recent call last):
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\util.py", line 96, in ensure_async
    result = await obj
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\jupyter_client\channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 754, in _async_poll_for_reply
    await self._async_handle_timeout(timeout, cell)
  File "C:\Users\straa005\Anaconda3\envs\sml\lib\site-packages\nbclient\client.py", line 801, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['# create helper function ', 'def stack_landsat_bands(band_path_template, out_path, bands, labels):', '    """Read the 30 m resolution files from disk and output with band names in long_format.', '    band_path: f-string of the path to the bands on disk. {band} should contain the band number', '    out_path:  path to the new output file']
...
["stack_landsat_bands(path_template, pjoin(scratch_dir, 'LS_stacked_2015.tif'), ls_bands.band, ls_bands.label)", '', "ls_2015 = rioxarray.open_rasterio(pjoin(scratch_dir, 'LS_stacked_2015.tif'), mask_and_scale=True)", 'fig, ax = plt.subplots(1,1)', 'ls_2015[3].plot(ax=ax, vmin=5000, vmax=12000, add_labels=False)']
-------------------

